### ISSUE TITLE
download *.DbLib save github repo clone folder but get "connect failed check your connection settings"

### ISSUE THREAD

**Issue by jeffreyhu3** [issus/altium-library#93]
Hi guys,

I follow Getting start from https://altiumlibrary.com/GetStarted, and download Celestial Altium Library - altium_library.DbLib from portal, meanwhile save it to folder which clone from github repository. When I open it by Altium Designer, get nothing buy get error "connect failed check your connection settings". Please help me how to fix it.

![Screenshot_1](https://user-images.githubusercontent.com/31752738/135288079-eadd7845-b726-4ce7-9e8c-dda38e0f8f14.png)

**Comment by jeffreyhu3** [comment]
Fix this issue, following https://altiumlibrary.com/GetStarted/Troubleshooting item about **Steps to Fix Missing Driver**,  I just install MSSQL Native Client 64 Bit and the connection failed was fixed.

**Comment by tebbo123** [comment]
I installed the MSSQL native client 64 bit and i still have the same issue . 

- i don't have a an educational ISP
- TCP 1433 is enabled for Altium designer 22 on my firewall and antivirus
- i have enable network connections on Altium preferences 
- When i click on build to test the connection , i get the errors shown below !
![Uploading error message.png…]()
![error 2](https://github.com/issus/altium-library/assets/137587848/962f52d2-3a67-4cda-92d2-1f748b64c356)
